## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
import numpy as np

In [15]:
def arange_reversed(N):
    return np.arange(N - 1, -1, -1)

N = 10
K = 15
print(arange_reversed(N))
print(arange_reversed(K))

[9 8 7 6 5 4 3 2 1 0]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [24]:
def diag_N(N):
    #Использовала функцию из предыдущего задания
    return(np.diag(arange_reversed(N)))

my_matrix = diag_N(10)
print(my_matrix)

print(f'Сумма значений матрицы равна {sum(sum(my_matrix))}')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений матрицы равна 45


## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [34]:
from numpy import linalg

In [41]:
a = np.array([ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])
b = np.array([4, 12, -3])

print(a)
print(b)

[[4 2 1]
 [1 3 0]
 [0 5 4]]
[ 4 12 -3]


In [42]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4
Найти пользователя, больше всего похожего на next_user_stats

In [48]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32)

In [49]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [67]:
next_user_length = np.sqrt(sum([x ** 2 for x in next_user_stats]))

max_cos = 0
max_user = 0

for num, user in enumerate(users_stats):
    user_length = np.sqrt(sum([x ** 2 for x in user]))
    user_dot = np.dot(user, next_user_stats)
    cos_for_user = user_dot / (user_length * next_user_length)
    if cos_for_user > max_cos:
        max_cos = cos_for_user
        max_user = num + 1
        
print(f'Самый похожий пользователь - пользователь № {max_user}.')

Самый похожий пользователь - пользователь № 8.
